### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Real-Gecko** [ajventer/pyKAN#16]
Add KSP 1.2.1
```bash
./pyKAN addkspdir --kspdir "/home/realgecko/Games/Kerbal Space Program"
```
```bash
./pyKAN list_modules --allmods
```
```bash
Using KSP Directory:  /home/realgecko/Games/Kerbal Space Program
Traceback (most recent call last):
  File "./pyKAN", line 359, in <module>
    actions[options.action]['method']()
  File "./pyKAN", line 165, in list_modules
    if modid not in result or Version(result[modid]['version']) < Version(version):
  File "/home/realgecko/Downloads/pyKAN-0.1.0/libPyKAN/version.py", line 102, in __lt__
    return self.__cmp__(other) < 0
  File "/home/realgecko/Downloads/pyKAN-0.1.0/libPyKAN/version.py", line 91, in __cmp__
    if self.numpart(j) <= self.numpart(i):
  File "/home/realgecko/Downloads/pyKAN-0.1.0/libPyKAN/version.py", line 52, in numpart
    return int(''.join(re.findall('\d',s)))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by SYZYGY-DEV333** [comment]
have you tried putting backslashes before the spaces in the string containing the path to your kspdir? I have no idea whether it will work, but maybe try it...?

**Comment by ajventer** [comment]
This problem is fixed already I believe.
